<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
 <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"/>
 <PropertyGroup><OutputType>WinExe</OutputType><TargetFrameworkVersion>v4.8</TargetFrameworkVersion><RootNamespace>Polesie</RootNamespace><AssemblyName>Polesie.postgresql</AssemblyName><OutputPath>bin\Debug\</OutputPath><LangVersion>7.3</LangVersion><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType><DefineConstants>POSTGRESQL</DefineConstants></PropertyGroup>
 <ItemGroup><Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Data"/><Reference Include="System.Drawing"/><Reference Include="System.Windows.Forms"/><Reference Include="System.Web.Extensions"/></ItemGroup>
 <ItemGroup><Compile Include="..\shared\**\*.cs" Exclude="..\shared\UI\LoginForm*.cs;..\shared\UI\MainForm*.cs"><Link>%(RecursiveDir)%(Filename)%(Extension)</Link></Compile></ItemGroup>
 <ItemGroup><PackageReference Include="Npgsql" Version="4.1.14"/><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All"/></ItemGroup>
 <ItemGroup><Content Include="Sql\*.sql"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content><Content Include="..\shared\Assets\*.png"><Link>Assets\%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup>
 <ItemGroup><PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.8.0" PrivateAssets="All"/></ItemGroup>
 <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
 <ItemGroup><Compile Include="..\shared\UI\LoginForm.cs"><Link>UI\LoginForm.cs</Link><SubType>Form</SubType></Compile><Compile Include="..\shared\UI\LoginForm.Designer.cs"><Link>UI\LoginForm.Designer.cs</Link><DependentUpon>LoginForm.cs</DependentUpon></Compile></ItemGroup>
 <ItemGroup><Compile Include="..\shared\UI\MainForm.cs"><Link>UI\MainForm.cs</Link><SubType>Form</SubType></Compile><Compile Include="..\shared\UI\MainForm.Designer.cs"><Link>UI\MainForm.Designer.cs</Link><DependentUpon>MainForm.cs</DependentUpon></Compile></ItemGroup>
</Project>
