<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DatabaseStack Condition="'$(DatabaseStack)'==''">mysql</DatabaseStack>
    <BaseIntermediateOutputPath>obj\$(DatabaseStack)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"/>
  <PropertyGroup>
    <DatabaseStack Condition="'$(DatabaseStack)'==''">mysql</DatabaseStack>
    <OutputType>Exe</OutputType><TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>Polesie.Checks</AssemblyName><OutputPath>..\..\.qa\checks\$(DatabaseStack)\</OutputPath>
    <LangVersion>7.3</LangVersion><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup><Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Data"/><Reference Include="System.Drawing"/><Reference Include="System.Windows.Forms"/><Reference Include="System.Web.Extensions"/></ItemGroup>
  <ItemGroup><Compile Include="Runner.cs"/><Compile Include="Checks.cs"/></ItemGroup>
  <ItemGroup><ProjectReference Include="..\..\examples\$(DatabaseStack)\Polesie.csproj"/></ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.8.0" PrivateAssets="All"/><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All"/></ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
</Project>
