(function(root){
'use strict';let panel,marked,launcher,index=0,route=[];
const candidates=[['.source-download','Исходные материалы','Скачайте официальный комплект. Excel и JSON понадобятся для построения схемы.'],['.toolbar','Выберите режим','«Разбор» объясняет шаги. «Моя тренировка» и «Пробный экзамен» предназначены для самостоятельной работы.'],['.module-grid','Пять модулей','Выберите модуль. Начните с модели данных, затем переходите к базе и приложению.'],['.lesson-stack','Выберите СУБД','MySQL и PostgreSQL используют разные SQL-примеры. Выбор применяется ко всему разбору.'],['.lesson-route-tabs','Пошагово или готовый пример','Сначала пройдите объяснение, затем сравните с готовым решением.'],['#er-launch','Интерактивная ER-справка','Здесь таблицы строятся по шагам. Нажмите поле или стрелку, чтобы увидеть источник и причину появления.'],['#presentation-launch','Презентация разбора','Откройте слайды для занятия или повторения.'],['.practice-intro','Самостоятельная работа','Читайте условия выбранного варианта и сохраняйте результаты в своей папке.'],['.submission-guide','Сохранение результата','Сайт сохраняет прогресс в браузере, но не отправляет ваши SQL, PDF и приложение. Здесь описано, куда сохранять работу.']];
function close(){marked?.classList.remove('tour-mark');panel?.remove();panel=null;document.removeEventListener('keydown',key);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);launcher?.isConnected&&launcher.focus();}
function placement(r,w,h,vw,vh){const gap=16,pad=12,clamp=(v,max)=>Math.max(pad,Math.min(v,max));let left,top,side;
 if(vw-r.right>=w+gap+pad){left=r.right+gap;top=clamp(r.top,vh-h-pad);side='right';}
 else if(r.left>=w+gap+pad){left=r.left-w-gap;top=clamp(r.top,vh-h-pad);side='left';}
 else if(vh-r.bottom>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.bottom+gap;side='below';}
 else if(r.top>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.top-h-gap;side='above';}
 else{left=clamp(r.left,vw-w-pad);top=clamp(r.bottom+gap,vh-h-pad);side='below';}
 return {left,top,side};}
function position(){if(!panel||!marked)return;const r=marked.getBoundingClientRect(),p=placement(r,panel.offsetWidth,panel.offsetHeight,document.documentElement.clientWidth,innerHeight);panel.style.left=p.left+'px';panel.style.top=p.top+'px';panel.dataset.side=p.side;}
function key(e){if(e.key==='Escape'){e.preventDefault();close();}}
function draw(){marked?.classList.remove('tour-mark');const [selector,title,body]=route[index];marked=document.querySelector(selector);if(!marked){close();return;}marked.classList.add('tour-mark');marked.scrollIntoView({block:'center',behavior:'instant'});panel.innerHTML='<span class="small">ТУР ПО САЙТУ · '+(index+1)+' / '+route.length+'</span><h3 id="tour-title">'+title+'</h3><p>'+body+'</p><div class="tour-actions"><button class="btn" id="tour-back" '+(!index?'disabled':'')+'>Назад</button><button class="btn primary" id="tour-next">'+(index===route.length-1?'Завершить':'Далее')+'</button><button class="btn" id="tour-stop">Закрыть тур</button></div>';panel.querySelector('#tour-back').onclick=()=>{index--;draw();};panel.querySelector('#tour-next').onclick=()=>{if(index===route.length-1)close();else{index++;draw();}};panel.querySelector('#tour-stop').onclick=close;position();panel.querySelector('#tour-next').focus({preventScroll:true});}
function start(){if(panel)close();launcher=document.activeElement;route=candidates.filter(([s])=>document.querySelector(s));index=0;panel=document.createElement('section');panel.className='tour-coach';panel.setAttribute('role','region');panel.setAttribute('aria-labelledby','tour-title');panel.setAttribute('aria-live','polite');document.body.append(panel);document.addEventListener('keydown',key);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);draw();}
root.ExamProductTour={placement,mount(){if(panel)close();const b=document.createElement('button');b.className='btn';b.id='product-tour-launch';b.textContent='Тур по сайту';b.onclick=start;document.querySelector('.top-tools').append(b);}};
})(globalThis);
