(function(root){
'use strict';let panel,marked,launcher,index=0,route=[];
let tourTitle='ТУР ПО САЙТУ',tourHost=null;
const guides={
 er:{title:'ГИД ПО ER-СХЕМЕ',steps:[['#er-steps','Учимся по шагам','Таблицы и поля добавляются последовательно. Область схемы сама перемещается к текущему элементу.'],['#er-jump','Выбрать этап','Можно перейти прямо к нужному полю. Номер этапа сохраняется в браузере.'],['#er-full','Обзор готовой схемы','В общем обзоре видны все таблицы. Нажмите таблицу, чтобы приблизить её до читаемого масштаба.'],['.er-dialog .er-zoom','Масштаб и положение','«К текущему элементу» возвращает к месту работы в 100%. «Вся схема» показывает общий план. Масштаб страницы менять не нужно.'],['.er-dialog .er-scroll','Таблицы, поля и стрелки','Нажмите поле или стрелку. 1 : N означает «один ко многим». Стрелка идёт от FK к PK.'],['.er-dialog .er-explanation','Источник и причина','Наверху справки указан файл и ячейка Excel или свойство JSON. Если поле придумано при проектировании, это явно отмечено. Ниже — объяснение и имя в СУБД.'],['.er-dialog .er-links','Список связей','Раскройте список для выбора связи словами, если линии на большой схеме трудно проследить.'],['#er-next','Следующий шаг','Продолжайте построение. Новый элемент появится в видимой части схемы, а справа обновится объяснение.']]},
 lesson:{title:'ГИД ПО РАЗБОРУ',steps:[['.lesson-stack','Выберите свою СУБД','SQL и скачиваемый пример должны соответствовать выбранной базе: MySQL или PostgreSQL.'],['.lesson-route-tabs','Выберите способ изучения','Начните с пошагового объяснения. Готовый пример используйте для сравнения после своей попытки.'],['.lesson-toc','Перейти к нужному действию','Содержание ведёт к конкретным шагам разбора.'],['#er-launch','Построение модели','В модулях 1 и 2 доступна интерактивная ER-справка с источниками всех полей.'],['#presentation-launch','Разбор в слайдах','Удобен для занятия с преподавателем и повторения.'],['.submission-guide','Сохраните собственную работу','Результат выполняется в вашей СУБД и программе. Сохраните SQL, PDF и проект в папку сдачи.']]},
 practice:{title:'ГИД ПО ПРАКТИКЕ',steps:[['#mock-variant','Выберите вариант','Перед началом проверьте номер своего пробного варианта. Его задания связаны между собой.'],['.practice-nav','Выберите задание','Кнопки переключают модули текущей работы. Отметки и таймер относятся к выбранному режиму и варианту.'],['.practice-downloads','Скачайте материалы','Используйте файлы именно выбранного задания.'],['.practice-condition','Прочитайте условие','Сначала выясните требуемый результат, затем работайте в своей СУБД и редакторе.'],['#practice-start','Запуск времени','Тур не запускает таймер. Нажмите «Начать» самостоятельно, когда готовы.'],['#practice-pause','Пауза','В тренировке можно приостановить время. В пробном экзамене ориентируйтесь на доступность кнопки и правила режима.'],['.self-check','Самопроверка','Сверьте свой результат с пунктами проверки. Отметка выполнения не является автоматической оценкой.'],['#practice-done','Отметить задание','Отмечайте завершение после проверки результата.'],['#practice-finish','Завершить работу','Завершение сохраняет локальный протокол, но не отправляет ваши файлы.']]},
 deck:{title:'ГИД ПО ПРЕЗЕНТАЦИИ',steps:[['.deck-dialog .slide-body','Текущий слайд','На слайде показана часть разбора выбранного модуля и СУБД.'],['#slide-next','Листать разбор','Переходите вперёд и назад кнопками. Для клавиатуры доступны стрелки, PageUp и PageDown.'],['#deck-toc','Содержание слайдов','Можно сразу перейти к нужной теме.'],['#deck-full','Полный экран','Разверните презентацию для показа группе.'],['.deck-dialog [data-close]','Вернуться к работе','Закрытие презентации возвращает к разбору; позиция слайда сохраняется.']]},
 downloads:{title:'ГИД ПО ФАЙЛАМ',steps:[['.example-download-buttons','Выберите нужный проект','Скачайте архив для своей СУБД. Примеры MySQL и PostgreSQL содержат разные подключения и SQL.'],['.submission-guide','Где хранить результат','Скачанный пример — учебный материал. Собственную работу сохраняйте отдельно в папке сдачи.'],['.source-download','Где исходные документы','Официальные исходные материалы доступны отдельным архивом наверху страницы.']]}
};
const candidates=[['.source-download','Исходные материалы','Скачайте официальный комплект. Excel и JSON понадобятся для построения схемы.'],['.toolbar','Выберите режим','«Разбор» объясняет шаги. «Моя тренировка» и «Пробный экзамен» предназначены для самостоятельной работы.'],['.module-grid','Пять модулей','Выберите модуль. Начните с модели данных, затем переходите к базе и приложению.'],['.lesson-stack','Выберите СУБД','MySQL и PostgreSQL используют разные SQL-примеры. Выбор применяется ко всему разбору.'],['.lesson-route-tabs','Пошагово или готовый пример','Сначала пройдите объяснение, затем сравните с готовым решением.'],['#er-launch','Интерактивная ER-справка','Здесь таблицы строятся по шагам. Нажмите поле или стрелку, чтобы увидеть источник и причину появления.'],['#presentation-launch','Презентация разбора','Откройте слайды для занятия или повторения.'],['.practice-intro','Самостоятельная работа','Читайте условия выбранного варианта и сохраняйте результаты в своей папке.'],['.submission-guide','Сохранение результата','Сайт сохраняет прогресс в браузере, но не отправляет ваши SQL, PDF и приложение. Здесь описано, куда сохранять работу.']];
function close(){marked?.classList.remove('tour-mark');panel?.remove();panel=null;tourHost?.removeEventListener('close',close);tourHost=null;document.removeEventListener('keydown',key);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);launcher?.isConnected&&launcher.focus({preventScroll:true});}
function placement(r,w,h,vw,vh){const gap=16,pad=12,clamp=(v,max)=>Math.max(pad,Math.min(v,max));let left,top,side;
 if(vw-r.right>=w+gap+pad){left=r.right+gap;top=clamp(r.top,vh-h-pad);side='right';}
 else if(r.left>=w+gap+pad){left=r.left-w-gap;top=clamp(r.top,vh-h-pad);side='left';}
 else if(vh-r.bottom>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.bottom+gap;side='below';}
 else if(r.top>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.top-h-gap;side='above';}
 else{left=clamp(r.left,vw-w-pad);top=clamp(r.bottom+gap,vh-h-pad);side='below';}
 return {left,top,side};}
function position(){if(!panel||!marked)return;const r=marked.getBoundingClientRect(),p=placement(r,panel.offsetWidth,panel.offsetHeight,document.documentElement.clientWidth,innerHeight);panel.style.left=p.left+'px';panel.style.top=p.top+'px';panel.dataset.side=p.side;}
function key(e){if(e.key==='Escape'){e.preventDefault();close();}}
function draw(){marked?.classList.remove('tour-mark');const [selector,title,body]=route[index];marked=document.querySelector(selector);if(!marked){close();return;}marked.classList.add('tour-mark');marked.scrollIntoView({block:'center',behavior:'instant'});panel.innerHTML='<span class="small">'+tourTitle+' · '+(index+1)+' / '+route.length+'</span><h3 id="tour-title">'+title+'</h3><p>'+body+'</p><div class="tour-actions"><button class="btn" id="tour-back" '+(!index?'disabled':'')+'>Назад</button><button class="btn primary" id="tour-next">'+(index===route.length-1?'Завершить':'Далее')+'</button><button class="btn" id="tour-stop">Закрыть тур</button></div>';panel.querySelector('#tour-back').onclick=()=>{index--;draw();};panel.querySelector('#tour-next').onclick=()=>{if(index===route.length-1)close();else{index++;draw();}};panel.querySelector('#tour-stop').onclick=close;position();panel.querySelector('#tour-next').focus({preventScroll:true});}
function start(scope){if(panel)close();launcher=document.activeElement;const guide=guides[scope];tourTitle=guide?.title||'ТУР ПО САЙТУ';route=(guide?.steps||candidates).filter(([s])=>{const e=document.querySelector(s);return e&&e.getClientRects().length&&!e.closest('[hidden]');});if(!route.length)return;index=0;panel=document.createElement('section');panel.className='tour-coach';panel.setAttribute('role','region');panel.setAttribute('aria-labelledby','tour-title');panel.setAttribute('aria-live','polite');tourHost=launcher?.closest('dialog')||null;(tourHost||document.body).append(panel);tourHost?.addEventListener('close',close);document.addEventListener('keydown',key);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);draw();}
function add(scope,host,label){if(!host||host.querySelector('[data-guide="'+scope+'"]'))return;const b=document.createElement('button');b.type='button';b.className='btn context-guide';b.dataset.guide=scope;b.textContent=label;b.onclick=()=>start(scope);host.append(b);}
root.ExamProductTour={placement,start,add,close,active:()=>!!panel,mount(){if(panel)close();const b=document.createElement('button');b.className='btn';b.id='product-tour-launch';b.textContent='Тур по сайту';b.onclick=()=>start();document.querySelector('.top-tools').append(b);add('lesson',document.querySelector('.lesson-route-tabs'),'Гид по разбору');add('practice',document.querySelector('.practice-intro'),'Гид по практике');add('downloads',document.querySelector('.example-downloads'),'Гид по файлам');}};
})(globalThis);
