(function(root){
'use strict';let panel,marked,launcher,index=0,route=[];
let tourTitle='ТУР ПО САЙТУ',tourHost=null;
const guides={
 teacher:{"title":"ГИД ПО ПОДГОТОВКЕ ПРЕЗЕНТАЦИИ","steps":[["#teacher-module","Выберите тему занятия","Выберите один из пяти модулей. Презентация будет посвящена именно ему."],["#teacher-stack","Выберите СУБД","В показ попадут SQL и примеры для MySQL или PostgreSQL."],["#teacher-view","Выберите материал","«Пошаговый разбор» объясняет создание результата, «Готовый пример» — работу с подготовленным решением."],["#teacher-settings","Подпишите презентацию","Укажите данные преподавателя и ссылку на материалы. Они появятся на титульном слайде."],["#presentation-launch","Откройте показ","Нажмите «Открыть презентацию». В её верхней панели есть отдельный «Гид по презентации»: он объясняет листание, содержание и полный экран."]]},
 mock:{title:'ГИД ПО ПРОБНОМУ ЭКЗАМЕНУ',steps:[['#mock-variant','Ваш вариант','Выберите номер по списку группы. Документы и задания относятся к этому варианту.'],['.practice-main','Материалы и подготовка','Условия и исходные данные можно читать прямо на сайте. Подготовьте программы и папку для своей работы.'],['.prepared','Готовность к началу','Отметьте подготовленные пункты. Тур сам не запускает отсчёт.'],['#practice-start','150 минут на пять модулей','После запуска время идёт непрерывно. Переходы между разделами и перезагрузка его не останавливают.'],['.practice-nav','Пять связанных заданий','Выполняйте модули последовательно, используя свои результаты.'],['#practice-finish','Завершение','Сначала сохраните файлы работы, затем завершите попытку. Протокол содержит время и отметки.']]},
 er:{title:'ГИД ПО ER-СХЕМЕ',steps:[['#er-steps','Учимся по шагам','Таблицы и поля добавляются последовательно. Область схемы сама перемещается к текущему элементу.'],['#er-jump','Выбрать этап','Можно перейти прямо к нужному полю. Номер этапа сохраняется в браузере.'],['#er-full','Обзор готовой схемы','Открывает отдельное окно на весь экран. Закройте его, чтобы продолжить с прежнего шага.'],['.er-dialog .er-zoom','Масштаб и положение','«К текущему элементу» возвращает к месту работы в 100%. «Вся схема» показывает общий план. Масштаб страницы менять не нужно.'],['.er-dialog .er-scroll','Таблицы, поля и стрелки','Нажмите поле или стрелку. 1 : N означает «один ко многим». Стрелка идёт от FK к PK.'],['.er-dialog .er-explanation','Источник и причина','Наверху справки указан файл и ячейка Excel или свойство JSON. Если поле придумано при проектировании, это явно отмечено. Ниже — объяснение и имя в СУБД.'],['.er-dialog .er-links','Список связей','Раскройте список для выбора связи словами, если линии на большой схеме трудно проследить.'],['#er-next','Следующий шаг','Продолжайте построение. Новый элемент появится в видимой части схемы, а справа обновится объяснение.']]},
 lesson:{title:'ГИД ПО РАЗБОРУ',steps:[['.module-grid','Выберите модуль','Начните со схемы, затем создайте базу, запрос, приложение и документацию.'],['.lesson-stack','Выберите свою СУБД','SQL и скачиваемый пример должны соответствовать выбранной базе: MySQL или PostgreSQL.'],['.source-files','Посмотрите исходные файлы','Раскройте список для просмотра Excel, JSON и документов прямо на сайте.'],['.lesson-toc','Перейти к нужному действию','Содержание ведёт к конкретным шагам разбора.'],['#er-launch','Построение модели','В модулях 1 и 2 доступна интерактивная ER-справка с источниками всех полей.'],['.submission-guide','Сохраните собственную работу','Результат выполняется в вашей СУБД и программе. Сохраните SQL, PDF и проект в папку сдачи.']]},
 practice:{title:'ГИД ПО ПРАКТИКЕ',steps:[['#mock-variant','Выберите вариант','Перед началом проверьте номер своего пробного варианта. Его задания связаны между собой.'],['.practice-nav','Выберите задание','Кнопки переключают модули текущей работы. Отметки и таймер относятся к выбранному режиму и варианту.'],['.practice-downloads','Скачайте материалы','Используйте файлы именно выбранного задания.'],['.practice-condition','Прочитайте условие','Сначала выясните требуемый результат, затем работайте в своей СУБД и редакторе.'],['#practice-start','Запуск времени','Тур не запускает таймер. Нажмите «Начать» самостоятельно, когда готовы.'],['#practice-pause','Пауза','В тренировке можно приостановить время. В пробном экзамене ориентируйтесь на доступность кнопки и правила режима.'],['.self-check','Самопроверка','Сверьте свой результат с пунктами проверки. Отметка выполнения не является автоматической оценкой.'],['#practice-done','Отметить задание','Отмечайте завершение после проверки результата.'],['#practice-finish','Завершить работу','Завершение сохраняет локальный протокол, но не отправляет ваши файлы.']]},
 deck:{"title":"ГИД ПО ПРЕЗЕНТАЦИИ","steps":[[".deck-dialog .slide-body h2","Тема текущего слайда","Слайды соответствуют выбранному модулю и СУБД. Изображения можно увеличивать нажатием, а полный код — открывать отдельной кнопкой на слайде с кодом."],[".deck-controls","Листайте слайды","Кнопки «Назад» и «Вперёд» переключают слайды. После щелчка по содержимому также работают стрелки клавиатуры и PageUp / PageDown."],["#deck-toc","Перейдите к нужной теме","«Содержание» открывает список слайдов. Выберите тему, чтобы перейти к ней сразу."],["#deck-detail","Выберите объём объяснения","По умолчанию открыт краткий показ. «Подробный разбор» добавляет детали; «Краткий показ» возвращает компактный вариант."],["#deck-theme","Настройте фон","Переключите светлую или тёмную тему под освещение аудитории."],["#deck-full","Разверните презентацию","Кнопка включает полный экран браузера. Повторное нажатие возвращает обычный размер."],[".deck-dialog [data-close]","Вернитесь к подготовке","Завершите гид, затем нажмите «К материалам преподавателя». Позиция слайда сохраняется в этом браузере."]]},
 downloads:{"title":"ГИД ПО ПРИМЕРАМ ПРОЕКТОВ","steps":[["#example-module","Выберите результат модуля","Схема, база, запрос, приложение и документация находятся в одном разделе. Выберите, с чем хотите сравнить свою работу."],["#example-stack","Укажите свою базу данных","Выбор MySQL или PostgreSQL меняет инструкции и код готового примера. Используйте тот же вариант, что в своей программе."],[".example-download-buttons","Скачайте полный проект","Архив содержит исходники и SQL выбранной СУБД. Распакуйте его целиком: общая папка shared должна остаться рядом с папкой проекта."],[".lesson-toc","Найдите нужное действие","Содержание ведёт к шагам запуска и проверки. В модуле 4 здесь описаны сборка, подключение к базе и вход в приложение."],[".study-controls","Просматривайте пример по шагам","Нажимайте «Назад» и «Далее» или включите «Показать все шаги». Код раскрывается по названию файла; снимок увеличивается поверх страницы."],[".example-download-buttons a[href=\"verification.html\"]","Посмотрите результаты проверки","Здесь указано, как проверялись архивы. Для запуска на вашем компьютере нужны сервер базы и собственные настройки подключения."]]}
};
const candidates=[['.site-nav','Разделы сайта','Учебные действия, работа в программах, критерии и инструменты преподавателя находятся в отдельных разделах.'],['.source-download','Исходные материалы','Скачайте официальный комплект. Excel и JSON понадобятся для построения схемы.'],['.toolbar','Выберите режим','«Разбор» объясняет шаги. «Моя тренировка» и «Пробный экзамен» предназначены для самостоятельной работы.'],['.module-grid','Пять модулей','Выберите модуль. Начните с модели данных, затем переходите к базе и приложению.'],['.lesson-stack','Выберите СУБД','MySQL и PostgreSQL используют разные SQL-примеры. Выбор применяется ко всему разбору.'],['.source-files','Исходные файлы','Раскройте список: файлы можно прочитать здесь или скачать. Готовое решение находится в «Примерах проектов».'],['#er-launch','Интерактивная ER-справка','Здесь таблицы строятся по шагам. Нажмите поле или стрелку, чтобы увидеть источник и причину появления.'],['.practice-intro','Самостоятельная работа','Читайте условия выбранного варианта и сохраняйте результаты в своей папке.'],['.submission-guide','Сохранение результата','Сайт сохраняет прогресс в браузере, но не отправляет ваши SQL, PDF и приложение. Здесь описано, куда сохранять работу.']];
function close(){marked?.classList.remove('tour-mark');panel?.remove();panel=null;tourHost?.removeEventListener('close',close);tourHost=null;document.removeEventListener('keydown',key);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);launcher?.isConnected&&launcher.focus({preventScroll:true});}
function placement(r,w,h,vw,vh){const gap=16,pad=12,clamp=(v,max)=>Math.max(pad,Math.min(v,max));let left,top,side;
 if(vw-r.right>=w+gap+pad){left=r.right+gap;top=clamp(r.top,vh-h-pad);side='right';}
 else if(r.left>=w+gap+pad){left=r.left-w-gap;top=clamp(r.top,vh-h-pad);side='left';}
 else if(vh-r.bottom>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.bottom+gap;side='below';}
 else if(r.top>=h+gap+pad){left=clamp(r.left,vw-w-pad);top=r.top-h-gap;side='above';}
 else{left=clamp(r.left,vw-w-pad);top=clamp(r.bottom+gap,vh-h-pad);side='below';}
 return {left,top,side};}
function position(){if(!panel||!marked)return;const r=marked.getBoundingClientRect(),p=placement(r,panel.offsetWidth,panel.offsetHeight,document.documentElement.clientWidth,innerHeight);panel.style.left=p.left+'px';panel.style.top=p.top+'px';panel.dataset.side=p.side;}
function key(e){if(e.key==='Escape'){e.preventDefault();close();}}
function draw(){marked?.classList.remove('tour-mark');const [selector,title,body]=route[index];marked=document.querySelector(selector);if(!marked){close();return;}marked.classList.add('tour-mark');marked.scrollIntoView({block:'center',behavior:'instant'});panel.innerHTML='<span class="small">'+tourTitle+' · '+(index+1)+' / '+route.length+'</span><h3 id="tour-title">'+title+'</h3><p>'+body+'</p><div class="tour-actions"><button class="btn" id="tour-back" '+(!index?'disabled':'')+'>Назад</button><button class="btn primary" id="tour-next">'+(index===route.length-1?'Завершить':'Далее')+'</button><button class="btn" id="tour-stop">Закрыть тур</button></div>';panel.querySelector('#tour-back').onclick=()=>{index--;draw();};panel.querySelector('#tour-next').onclick=()=>{if(index===route.length-1)close();else{index++;draw();}};panel.querySelector('#tour-stop').onclick=close;position();panel.querySelector('#tour-next').focus({preventScroll:true});}
function start(scope){if(panel)close();launcher=document.activeElement;const guide=guides[scope];tourTitle=guide?.title||'ТУР ПО САЙТУ';route=(guide?.steps||candidates).filter(([s])=>{const e=document.querySelector(s);return e&&e.getClientRects().length&&!e.closest('[hidden]');});if(!route.length)return;index=0;panel=document.createElement('section');panel.className='tour-coach';panel.setAttribute('role','region');panel.setAttribute('aria-labelledby','tour-title');panel.setAttribute('aria-live','polite');tourHost=launcher?.closest('dialog')||null;(tourHost||document.body).append(panel);tourHost?.addEventListener('close',close);document.addEventListener('keydown',key);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);draw();}
function add(scope,host,label){if(!host||host.querySelector('[data-guide="'+scope+'"]'))return;const b=document.createElement('button');b.type='button';b.className='btn context-guide';b.dataset.guide=scope;b.textContent=label;b.onclick=()=>start(scope);host.append(b);}
root.ExamProductTour={placement,start,add,close,active:()=>!!panel,mount(){if(panel)close();const b=document.createElement('button');b.className='btn';b.id='product-tour-launch';b.textContent='Тур по сайту';b.onclick=()=>start(document.querySelector('.examples-intro')?'downloads':document.querySelector('.teacher-page')?'teacher':undefined);document.querySelector('.top-tools').append(b);add('lesson',document.querySelector('.module-heading'),'Гид');add(document.querySelector('#mock-variant')?'mock':'practice',document.querySelector('.practice-heading'),'Гид');add('downloads',document.querySelector('.examples-heading'),'Гид по примерам');add('teacher',document.querySelector('#teacher-actions'),'Гид по презентации');}};
})(globalThis);
