(function(root){
 'use strict';let ctx,dialog;const E=v=>root.ExamCore.escape(v);
 function render(stack){return '<section class="program-page"><span class="section-code">СПРАВКА · ДЕЙСТВИЯ В ПРОГРАММАХ</span><h1>Работа в программах</h1><p>Откройте инструкцию рядом с программой. На каждом шаге: действие и проверка результата. Для phpMyAdmin, SQL и Visual Studio добавлены снимки работающих программ.</p><label class="program-stack-picker">База данных для приложения<select id="program-stack"><option value="mysql" '+(stack==='mysql'?'selected':'')+'>MySQL</option><option value="postgresql" '+(stack==='postgresql'?'selected':'')+'>PostgreSQL</option></select></label><div class="program-grid">'+Object.entries(root.PROGRAM_GUIDES).filter(([id])=>id!=='postgresql').map(([id,g])=>'<article class="program-card"><span class="section-code">'+E(g.label)+'</span><h2>'+E(g.title)+'</h2><p>'+E(g.description)+'</p><button class="btn primary" data-program="'+id+'">Открыть '+g.steps.length+' шагов →</button></article>').join('')+'</div><article class="program-card"><h2>PostgreSQL · pgAdmin</h2><p>Тот же маршрут: база → таблицы → ключи → данные → запрос → сохранение. Пошаговое объяснение действий в pgAdmin.</p><button class="btn" data-program="postgresql">Открыть инструкцию</button></article></section>';}
 function open(id){const source=root.PROGRAM_GUIDES[id];if(!source)return;const guide=JSON.parse(JSON.stringify(source).replaceAll('{{stack}}',ctx.stack));const launcher=document.activeElement,key='program-guide-v2:'+id+':'+ctx.stack;let index=Math.max(0,Math.min(guide.steps.length-1,Number(ctx.get(key))||0));dialog=document.createElement('dialog');dialog.className='program-dialog';dialog.setAttribute('aria-labelledby','program-title');document.body.append(dialog);dialog.addEventListener('close',()=>{dialog.remove();launcher?.isConnected&&launcher.focus();});
 function draw(){const step=guide.steps[index];dialog.innerHTML='<header class="program-head"><div><span class="section-code">ПОШАГОВАЯ СПРАВКА'+(id==='visualstudio'?' · '+(ctx.stack==='mysql'?'MySQL':'PostgreSQL'):'')+'</span><h2 id="program-title">'+E(guide.title)+'</h2></div><button class="btn" data-close>Закрыть</button></header><div class="program-content lesson '+(step.image?'has-image':'')+(step.controls?' has-controls':'')+'"><div class="program-instructions"><h3 tabindex="-1">'+(index+1)+'. '+E(step.title)+'</h3><p>'+E(step.goal)+'</p><ol>'+[...step.actions,...(step.actionsByStack?.[ctx.stack]||[])].map(a=>'<li>'+E(a)+'</li>').join('')+'</ol>'+(step.code?'<section class="program-code"><div class="code-actions"><button class="btn" data-copy-code>Копировать весь код</button></div><pre><code>'+E(step.code)+'</code></pre></section>':'')+''+extra(step)+(step.catalog?catalog():'')+'<p class="program-check"><strong>Проверьте:</strong> '+E(step.check)+'</p>'+(step.link?'<p><a class="btn" href="'+E(step.link.url)+'"'+(/\.zip$/i.test(step.link.url)?' download':'')+'>'+E(step.link.title)+'</a></p>':'')+'</div>'+(step.image?'<figure><a href="'+E(step.image)+'" aria-label="Увеличить снимок"><img src="'+E(step.image)+'" alt="'+E(step.caption||step.title)+'"></a><figcaption>'+E(step.caption||'Реальный экран программы. Нажмите, чтобы увеличить снимок поверх инструкции.')+'</figcaption></figure>':'')+'</div><footer class="program-footer"><button class="btn" data-prev '+(!index?'disabled':'')+'>← Назад</button><select class="program-jump" aria-label="Шаг инструкции">'+guide.steps.map((s,i)=>'<option value="'+i+'" '+(i===index?'selected':'')+'>'+(i+1)+'. '+E(s.title)+'</option>').join('')+'</select><button class="btn primary" data-next '+(index===guide.steps.length-1?'disabled':'')+'>Далее →</button></footer>';dialog.querySelector('[data-close]').onclick=()=>dialog.close();const go=n=>{index=n;ctx.set(key,String(index));draw();dialog.querySelector('h3').focus({preventScroll:true});};dialog.querySelector('[data-prev]').onclick=()=>go(index-1);dialog.querySelector('[data-next]').onclick=()=>go(index+1);dialog.querySelector('select').onchange=e=>go(Number(e.target.value));}
 dialog.showModal();draw();}
 function extra(step){return (step.controls?'<div class="scroll-table"><table><thead><tr><th>Компонент</th><th>(Name)</th><th>Родитель / событие</th><th>Свойства / метод</th></tr></thead><tbody>'+step.controls.map(row=>'<tr>'+row.map(v=>'<td>'+E(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'')+(step.files||[]).map(f=>'<details class="code-source"><summary>'+E(f.file.replace('examples/shared/',''))+' · полный код</summary><div class="code-actions"><button class="btn" data-copy-code>Копировать весь код</button></div><pre><code>'+E(f.code)+'</code></pre></details>').join('');}
 function catalog(){return '<details><summary>Все 11 таблиц и 49 полей: что вводить</summary>'+root.ER_GUIDE.stacks.mysql.tables.map(t=>'<h4>'+E(t.title)+' · '+E(t.id)+'</h4><div class="scroll-table"><table><thead><tr><th>Поле</th><th>Тип</th><th>NULL</th><th>Ключ</th></tr></thead><tbody>'+t.fields.map(f=>'<tr><td>'+E(f.title)+'<br><code>'+E(f.id)+'</code></td><td>'+E(f.type)+'</td><td>'+(f.nullable?'Можно':'Нельзя')+'</td><td>'+E([f.pk?'PK':'',f.fk?'FK':'',f.unique?'UNIQUE':''].filter(Boolean).join(', '))+'</td></tr>').join('')+'</tbody></table></div>').join('')+'<p>Составные ключи, значения по умолчанию и CHECK показаны в полном SQL. Сверьте их перед сохранением.</p><a href="code/examples/mysql/Sql/01-schema.sql.txt" target="_blank" rel="noopener">Полный SQL схемы</a></details>';}
 function mount(input){ctx=input;document.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>open(b.dataset.program));const initial=new URLSearchParams(location.search).get('guide');if(document.querySelector('.program-page')&&initial&&root.PROGRAM_GUIDES[initial]){const u=new URL(location.href);u.searchParams.delete('guide');history.replaceState(null,'',u);open(initial);}}
 root.ExamPrograms={render,mount,open};
})(globalThis);
